# Generated by Django 2.2.5 on 2019-11-07 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191107_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attach_type',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_read_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='member',
            name='new_messages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
