# Generated by Django 2.2.5 on 2019-11-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20191121_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(max_length=100, null=True, verbose_name='Последнее сообщение'),
        ),
    ]
