# Generated by Django 2.2.5 on 2019-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20191128_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
