# Generated by Django 2.2.5 on 2019-11-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191107_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=256, null=True, verbose_name='Аватар'),
        ),
    ]
